version: '2'

services:
  config-server:
    image: springcommunity/spring-petclinic-config-server:2.3.6
    container_name: config-server
    mem_limit: 768M
    ports:
     - 8888:8888
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"

  discovery-server:
    image: springcommunity/spring-petclinic-discovery-server:2.3.6
    container_name: discovery-server
    mem_limit: 768M
    depends_on:
      - config-server
    ports:
     - 8761:8761
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"

  #SPRING--------------------------------
  # customers-service:
  #   image: springcommunity/spring-petclinic-customers-service:2.3.6
  #   container_name: customers-service
  #   mem_limit: 768M
  #   depends_on:
  #   - config-server
  #   - discovery-server
  #   - mysql-server
  #   ports:
  #   - 8081:8081
  #   deploy:
  #     restart_policy:
  #       condition: on-failure
  #   environment:
  #     - "SPRING_PROFILES_ACTIVE=docker"

  #STEELTOE--------------------------------
  customers-service:
    image: springcommunity/steeltoe-customers-service:2.3.6
    build:
      context: ./steeltoe-petclinic-customers-service/Customers.Api
      args:
        - EXPOSED_PORT=8081
    container_name: customers-service
    mem_limit: 512M
    depends_on:
      - config-server
      - discovery-server
      #- mysql-server
    ports:
    - 8081:8081
    deploy:
      restart_policy:
        condition: on-failure

  #SPRING--------------------------------
  # visits-service:
  #   image: springcommunity/spring-petclinic-visits-service:2.3.6
  #   container_name: visits-service
  #   mem_limit: 768M
  #   depends_on:
  #   - config-server
  #   - discovery-server
  #   - mysql-server
  #   ports:
  #   - 8082:8082
  #   deploy:
  #     restart_policy:
  #       condition: on-failure
  #   environment:
  #     - "SPRING_PROFILES_ACTIVE=docker"

  #STEELTOE--------------------------------
  visits-service:
    image: springcommunity/steeltoe-visits-service:2.3.6
    build:
      context: ./steeltoe-petclinic-visits-service/Visits.Api
      args:
        - EXPOSED_PORT=8082
    container_name: visits-service
    mem_limit: 512M
    depends_on:
      - config-server
      - discovery-server
      #- mysql-server
    ports:
    - 8082:8082
    deploy:
      restart_policy:
        condition: on-failure

  #SPRING--------------------------------
  # vets-service:
  #   image: springcommunity/spring-petclinic-vets-service:2.3.6
  #   container_name: vets-service
  #   mem_limit: 768M
  #   depends_on:
  #   - config-server
  #   - discovery-server
  #   - mysql-server
  #   ports:
  #     - 8083:8083
  #   deploy:
  #     restart_policy:
  #       condition: on-failure
  #   environment:
  #     - "SPRING_PROFILES_ACTIVE=docker"

  #STEELTOE--------------------------------
  vets-service:
    image: springcommunity/steeltoe-vets-service:2.3.6
    build:
      context: ./steeltoe-petclinic-vets-service/Vets.Api
      args:
        - EXPOSED_PORT=8083
    container_name: vets-service
    mem_limit: 512M
    depends_on:
      - config-server
      - discovery-server
      #- mysql-server
    ports:
    - 8083:8083
    deploy:
      restart_policy:
        condition: on-failure

  api-gateway:
    image: springcommunity/spring-petclinic-api-gateway:2.3.6
    container_name: api-gateway
    mem_limit: 768M
    depends_on:
     - config-server
     - discovery-server
    ports:
     - 8080:8080
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    mem_limit: 512M
    environment:
    - JAVA_OPTS=-XX:+UnlockExperimentalVMOptions -Djava.security.egd=file:/dev/./urandom
    ports:
     - 9411:9411

  admin-server:
    image: springcommunity/spring-petclinic-admin-server:2.3.6
    container_name: admin-server
    mem_limit: 768M
    depends_on:
     - config-server
     - discovery-server
    ports:
     - 9090:9090
    deploy:
      restart_policy:
        condition: on-failure

  # mysql-server:
  #   image: mysql
  #   environment:
  #     MYSQL_DATABASE: petclinic
  #     MYSQL_ROOT_PASSWORD: petclinic
  #   ports:
  #   - 3306:3306

  ## Grafana / Prometheus

  grafana-server:
    build: ./docker/grafana
    container_name: grafana-server
    mem_limit: 256M
    ports:
    - 3000:3000

  prometheus-server:
    build: ./docker/prometheus
    container_name: prometheus-server
    mem_limit: 256M
    ports:
    - 9091:9090
