---
kind: ConfigMap
apiVersion: v1
metadata:
  name: steeltoe-apps
  namespace: petclinic
data:
  management__endpoints__actuator__exposure__include__0: "*"
  management__tracing__exporter__zipkin__endpoint: http://zipkin:9411/api/v2/spans
  logging__logLevel__Steeltoe: Trace

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: spring-apps
  namespace: petclinic
data:
  application.yaml: |-
    server:
      port: 8080
      shutdown: graceful
      lifecycle:
        timeout-per-shutdown-phase: 15
      compression:
        enabled: true
        mime-types: application/json,text/css,application/javascript
        min-response-size: 2048
    # Logging
    logging.level.org.springframework: INFO

    # Metrics
    management:
      endpoint:
        health:
          probes:
            enabled: true
      health:
        livenessState:
          enabled: true
        readinessState:
          enabled: true
        restart:
          enabled: true
        metrics:
          enabled: true
        prometheus:
          enabled: true
      endpoints:
        web:
          exposure:
            include: '*'
      metrics:
        export:
          prometheus:
            enabled: true
    spring:
      jpa:
        show-sql: true
        hibernate:
          ddl-auto: none
          generate-ddl: false
      sleuth:
        sampler:
          probability: 1.0
        config:
          # Allow the microservices to override the remote properties with their own System properties or config file
          allow-override: true
          # Override configuration with any local property source
          override-none: true
      messages:
        basename: messages/messages
      zipkin:
        base-url: http://zipkin:9411/
      cloud:
        kubernetes:
          discovery:
            enabled: true
        loadbalancer:
          ribbon:
            enabled: false
        gateway:
          x-forwarded:  
            enabled: true 
            for-enabled: true 
            proto-enabled: true 
            host-append: false  
            port-append: false  
            proto-append: false
    vets:
      cache:
        ttl: 60
        heap-size: 101
