---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zipkin
  namespace: petclinic
spec:
  selector:
    matchLabels:
      app: zipkin
  replicas: 1
  template:
    metadata:
      labels:
        app: zipkin
    spec:
      containers:
        - name: zipkin
          image: openzipkin/zipkin
          resources:
            requests:
              memory: 1Gi
              cpu: 250m
            limits:
              memory: 1Gi
              cpu: 500m
          ports:
          - containerPort: 9411

---
apiVersion: v1
kind: Service
metadata:
  name: zipkin
  namespace: petclinic
spec:
  ports:
    - port: 9411
  selector:
    app: zipkin
  type: LoadBalancer
